apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onpre-k8s-return-hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: araki.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onpre-k8s-return-hello
                port:
                  number: 8000
